In [3]:
import numpy as np

husband = np.array([120,150,190])
wife = np.array([130,130,130])
law_mother = np.array([2,3,2.5])

cur_rate = 72

law_mother_rub = law_mother*cur_rate

family_income = husband+wife+law_mother_rub

print('Доход тещи: {}\nДоход семьи: {}'.format(
    law_mother_rub, family_income
    ))

Доход тещи: [144. 216. 180.]
Доход семьи: [394. 496. 500.]


In [6]:
a = np.array([4,6])
b = np.array([-1,-2])
c = a + b 
c
len_c = np.sqrt(np.square(c[0]) + np.square(c[1]))
len_c

5.0

In [7]:
x = np.array([4,5])
y = np.array([2,1])
u = np.array([1,0])

s = 2*x + (-3)*y + 5*u
s

array([7, 7])

In [9]:
manufactered = np.array([3,4,5,9])
selled = np.array([1,5,3,6])

spended = 200*manufactered
income = 400*selled

balance = income - spended
balance

array([-200, 1200,  200,  600])

In [11]:
x = np.array([4,5,-1])
y = np.array([2,0,1])

c = np.dot(x,y)
c

7

**Задание 2.13**

In [17]:
x_list = [
    [4,2,-1],
    [4,5,-1],
    [4,-1],
    [4,-1]
    ]

y_list = [
    [2,0,1],
    [0,0,0],
    [-1,4],
    [1,4]
]

for iteraition, (x, y) in enumerate(zip(x_list, y_list)):
    x_array = np.array(x)
    y_array = np.array(y)

    if np.dot(x_array, y_array) == 0:
        print('Вектора под номером {} являются ортогональными (x={}, y={})'.format(
            (iteraition+1), x_list[iteraition], y_list[iteraition]
        ))
    


Вектора под номером 2 являются ортогональными (x=[4, 5, -1], y=[0, 0, 0])
Вектора под номером 4 являются ортогональными (x=[4, -1], y=[1, 4])


In [19]:
w = np.array([-6118, 220.8, 0, 332.2, 563, 0])

sample = np.array([1, 45, 1, 25.175, 2, 1])

prediction = np.dot(w,sample)

prediction

13307.135000000002

In [20]:
import pandas as pd

Hut_Paradise_DF = pd.DataFrame({
    '1.Rent': [65, 70, 120, 35, 40, 50, 100, 90, 85], 
    '2.Area': [50, 52, 80, 33, 33, 44, 80, 65, 65], 
    '3.Rooms':[3, 2, 1, 1, 1, 2, 4, 3, 2],
    '4.Floor':[5, 12, 10, 3, 6, 13, 8, 21, 5], 
    '5.Demo two weeks':[8, 4, 5, 10, 20, 12, 5, 1, 10], 
    '6.Liv.Area': [37, 40, 65, 20, 16, 35, 60, 50, 40]
})

In [23]:
Hut_Paradise_DF

1.Rent  2.Area  3.Rooms  4.Floor  5.Demo two weeks  6.Liv.Area
0      65      50        3        5                 8          37
1      70      52        2       12                 4          40
2     120      80        1       10                 5          65
3      35      33        1        3                10          20
4      40      33        1        6                20          16
5      50      44        2       13                12          35
6     100      80        4        8                 5          60
7      90      65        3       21                 1          50
8      85      65        2        5                10          40

In [22]:
Hut_Paradise_values = Hut_Paradise_DF.values
Hut_Paradise_values[4]

array([40, 33,  1,  6, 20, 16], dtype=int64)

In [26]:
Hut_Paradise_values[:,3]

array([ 5, 12, 10,  3,  6, 13,  8, 21,  5], dtype=int64)

In [27]:
not_liv_area = Hut_Paradise_values[:,1] - Hut_Paradise_values[:,5]
not_liv_area

array([13, 12, 15, 13, 17,  9, 20, 15, 25], dtype=int64)

In [30]:
observe_time = np.array([10,20,30,15,5,40,20,8,20])

In [32]:
observe_time_by_flat = observe_time * Hut_Paradise_values[:,4]
observe_time_by_flat

array([ 80,  80, 150, 150, 100, 480, 100,   8, 200], dtype=int64)

In [33]:
observe_time_by_flat.sum()

1348

In [34]:
u=np.array([3,0,1,1,1])
v=np.array([0,1,0,2,-2])
w=np.array([1,-4,-1,0,-2])

s = 2*v + (-3)*w
s

array([-3, 14,  3,  4,  2])

In [36]:
is_ort = u@s
is_ort

0

In [ ]:
import numpy as np

Husband_Income = np.array([100,220,140])
Wife_Income = np.array([150,200,130])
Mother_In_Law_Income = np.array([90,80,100])

Husband_Consumption = np.array([50,50,60])
Wife_Consumption = np.array([100,80,140])
Mother_In_Law_Consumption = np.array([100,20,140])

Inc = np.array([Husband_Income, Wife_Income, Mother_In_Law_Income]).T

Cons = np.array([Husband_Consumption, Wife_Consumption, Mother_In_Law_Consumption]).T
Cons
tax_coef = 1- 0.13
Inc_after_tax = tax_coef * Inc

balance = Inc_after_tax - Cons

balance     

array([[ 37. ,  30.5, -21.7],
       [141.4,  94. ,  49.6],
       [ 61.8, -26.9, -53. ]])

In [6]:
import numpy as np
A = np.array([[5,-1,3,1,2], [-2,8,5,-1,1]])
x = np.array([1,2,3,4,5])

B = A@x
B

array([26, 30])

In [7]:
A = np.array([[1,9,8,5], [3,6,3,2], [3,3,3,3], [0,2,5,9], [4,4,1,2]])
B = np.array([[1,-1,0,1,1], [-2,0,2,-1,1]])

C = B@A
C

array([[  2,   9,  11,  14],
       [  8, -10, -14, -11]])

In [11]:
x = np.array([1,2,1,0,4])
y = np.array([2,1,-1,1,0])
z = np.array([-1,1,-1,0,0])

A = np.array([x,y,z])

G = A.T@A
G

array([[ 6,  3,  0,  2,  4],
       [ 3,  6,  0,  1,  8],
       [ 0,  0,  3, -1,  4],
       [ 2,  1, -1,  1,  0],
       [ 4,  8,  4,  0, 16]])

In [12]:
import pandas as pd
import numpy as np

Count_DF = pd.DataFrame({
    'Женские стрижки': [10, 2, 12, 4, 6, 10, 22, 7], 
    'Мужские стрижки': [5, 21, 12, 8, 25, 3, 1, 0], 
    'Окрашивания':[12, 3, 0, 18, 27, 2, 4, 31],
    'Укладка':[15, 25, 30, 14, 25, 17, 25, 31],
    'Уход':[10, 6, 4, 5, 18, 12, 20, 28]
    }, 
    index=['Аня', 'Борис', 'Вика', 'Галя', 'Дима', 'Егор', 'Женя','Юра']
)
Price_DF = pd.DataFrame({
    'Женские стрижки': [2, 1.8, 2, 1.8, 2.5, 5, 1.1, 4.5], 
    'Мужские стрижки': [1.5, 2.5, 2, 1.2, 3.5, 5, 1, 4], 
    'Окрашивания':[1, 1, 0, 2.8, 2, 3, 1.5, 2.5],
    'Укладка':[0.8, 1, 0.5, 0.8, 1, 2, 0.5, 1],
    'Уход':[1, 1, 2, 2, 1.5, 2.5, 1.7, 2] 
    }, 
    index=['Аня', 'Борис', 'Вика', 'Галя', 'Дима', 'Егор', 'Женя','Юра']
)

In [13]:
Count_DF

Женские стрижки  Мужские стрижки  Окрашивания  Укладка  Уход
Аня                 10                5           12       15    10
Борис                2               21            3       25     6
Вика                12               12            0       30     4
Галя                 4                8           18       14     5
Дима                 6               25           27       25    18
Егор                10                3            2       17    12
Женя                22                1            4       25    20
Юра                  7                0           31       31    28

In [14]:
Price_DF

Женские стрижки  Мужские стрижки  Окрашивания  Укладка  Уход
Аня                2.0              1.5          1.0      0.8   1.0
Борис              1.8              2.5          1.0      1.0   1.0
Вика               2.0              2.0          0.0      0.5   2.0
Галя               1.8              1.2          2.8      0.8   2.0
Дима               2.5              3.5          2.0      1.0   1.5
Егор               5.0              5.0          3.0      2.0   2.5
Женя               1.1              1.0          1.5      0.5   1.7
Юра                4.5              4.0          2.5      1.0   2.0

In [23]:
income_df = Count_DF * Price_DF
income_df['sum'] = income_df.sum(axis=1)
income_array = np.array(income_df['sum'])
income_array
com = np.array([0.2, 0.2, 0.3, 0.1, 0.1])

# income_saloon = income_array * com
# income_saloon
print(income_array)
print(com)

[ 61.5  90.1  71.   88.4 208.5 135.   77.7 196. ]
[0.2 0.2 0.3 0.1 0.1]


In [31]:
price_arrays = np.array(Price_DF)
price_arrays

com_array_per_service = price_arrays * com
com_array_per_service

count_array = np.array(Count_DF)

count_array

array([[10,  5, 12, 15, 10],
       [ 2, 21,  3, 25,  6],
       [12, 12,  0, 30,  4],
       [ 4,  8, 18, 14,  5],
       [ 6, 25, 27, 25, 18],
       [10,  3,  2, 17, 12],
       [22,  1,  4, 25, 20],
       [ 7,  0, 31, 31, 28]], dtype=int64)

In [32]:
com_array_per_service

array([[0.4 , 0.3 , 0.3 , 0.08, 0.1 ],
       [0.36, 0.5 , 0.3 , 0.1 , 0.1 ],
       [0.4 , 0.4 , 0.  , 0.05, 0.2 ],
       [0.36, 0.24, 0.84, 0.08, 0.2 ],
       [0.5 , 0.7 , 0.6 , 0.1 , 0.15],
       [1.  , 1.  , 0.9 , 0.2 , 0.25],
       [0.22, 0.2 , 0.45, 0.05, 0.17],
       [0.9 , 0.8 , 0.75, 0.1 , 0.2 ]])

In [34]:
company_income = com_array_per_service * count_array

company_income_per_worker = company_income.sum(axis=1)

company_income_per_worker

array([11.3 , 15.22, 11.9 , 20.6 , 41.9 , 21.2 , 11.49, 38.25])

In [36]:
total_incomes = price_arrays * count_array

worker_incomes = total_incomes - company_income

worker_income_per_worker = worker_incomes.sum(axis=1)

worker_income_per_worker


array([ 50.2 ,  74.88,  59.1 ,  67.8 , 166.6 , 113.8 ,  66.21, 157.75])

In [38]:
A = np.array([[8, 6, 11], [7, 5, 9],[6, 10, 6]])

A_inv = np.linalg.inv(A)

A_inv

array([[-1.875  ,  2.3125 , -0.03125],
       [ 0.375  , -0.5625 ,  0.15625],
       [ 1.25   , -1.375  , -0.0625 ]])

In [48]:
v1 = np.array([9, 10, 7, 7, 9])
v2 = np.array([2, 0, 5, 1, 4])
v3 = np.array([4, 0, 0, 4, 1])
v4 = np.array([3, -4, 3, -1, -4])

A = np.array([v1, v2, v3, v4]).T

np.linalg.matrix_rank(A)

G = A.T@A
np.linalg.det(G)

G_inv = np.linalg.inv(G)

G_inv

array([[ 0.01711488, -0.02798543, -0.02623063,  0.01599775],
       [-0.02798543,  0.071967  ,  0.03031441, -0.02722776],
       [-0.02623063,  0.03031441,  0.07683106, -0.02640498],
       [ 0.01599775, -0.02722776, -0.02640498,  0.03479318]])

In [50]:
A = np.array([[1,1],[1,2]])
G = A.T@A
G

array([[2, 3],
       [3, 5]])

In [51]:
A = np.array([[1,2],[3,7]])
A_inv = np.linalg.inv(A)

A_inv

array([[ 7., -2.],
       [-3.,  1.]])

In [52]:
A = np.array([[2,10,-2],[3,2,-2],[8,14,-6]])

A_rang = np.linalg.matrix_rank(A)

A_rang


2

In [ ]:
A = np.array([[2,10,-2],[3,2,-2],[8,14,-6]])

A_rang = np.linalg.matrix_rank(A)

A_rang