In [3]:
import numpy as np

husband = np.array([120,150,190])
wife = np.array([130,130,130])
law_mother = np.array([2,3,2.5])

cur_rate = 72

law_mother_rub = law_mother*cur_rate

family_income = husband+wife+law_mother_rub

print('Доход тещи: {}\nДоход семьи: {}'.format(
    law_mother_rub, family_income
    ))

Доход тещи: [144. 216. 180.]
Доход семьи: [394. 496. 500.]


In [6]:
a = np.array([4,6])
b = np.array([-1,-2])
c = a + b 
c
len_c = np.sqrt(np.square(c[0]) + np.square(c[1]))
len_c

5.0

In [7]:
x = np.array([4,5])
y = np.array([2,1])
u = np.array([1,0])

s = 2*x + (-3)*y + 5*u
s

array([7, 7])

In [9]:
manufactered = np.array([3,4,5,9])
selled = np.array([1,5,3,6])

spended = 200*manufactered
income = 400*selled

balance = income - spended
balance

array([-200, 1200,  200,  600])

In [11]:
x = np.array([4,5,-1])
y = np.array([2,0,1])

c = np.dot(x,y)
c

7

**Задание 2.13**

In [17]:
x_list = [
    [4,2,-1],
    [4,5,-1],
    [4,-1],
    [4,-1]
    ]

y_list = [
    [2,0,1],
    [0,0,0],
    [-1,4],
    [1,4]
]

for iteraition, (x, y) in enumerate(zip(x_list, y_list)):
    x_array = np.array(x)
    y_array = np.array(y)

    if np.dot(x_array, y_array) == 0:
        print('Вектора под номером {} являются ортогональными (x={}, y={})'.format(
            (iteraition+1), x_list[iteraition], y_list[iteraition]
        ))
    


Вектора под номером 2 являются ортогональными (x=[4, 5, -1], y=[0, 0, 0])
Вектора под номером 4 являются ортогональными (x=[4, -1], y=[1, 4])


In [19]:
w = np.array([-6118, 220.8, 0, 332.2, 563, 0])

sample = np.array([1, 45, 1, 25.175, 2, 1])

prediction = np.dot(w,sample)

prediction

13307.135000000002

In [20]:
import pandas as pd

Hut_Paradise_DF = pd.DataFrame({
    '1.Rent': [65, 70, 120, 35, 40, 50, 100, 90, 85], 
    '2.Area': [50, 52, 80, 33, 33, 44, 80, 65, 65], 
    '3.Rooms':[3, 2, 1, 1, 1, 2, 4, 3, 2],
    '4.Floor':[5, 12, 10, 3, 6, 13, 8, 21, 5], 
    '5.Demo two weeks':[8, 4, 5, 10, 20, 12, 5, 1, 10], 
    '6.Liv.Area': [37, 40, 65, 20, 16, 35, 60, 50, 40]
})

In [23]:
Hut_Paradise_DF

1.Rent  2.Area  3.Rooms  4.Floor  5.Demo two weeks  6.Liv.Area
0      65      50        3        5                 8          37
1      70      52        2       12                 4          40
2     120      80        1       10                 5          65
3      35      33        1        3                10          20
4      40      33        1        6                20          16
5      50      44        2       13                12          35
6     100      80        4        8                 5          60
7      90      65        3       21                 1          50
8      85      65        2        5                10          40

In [22]:
Hut_Paradise_values = Hut_Paradise_DF.values
Hut_Paradise_values[4]

array([40, 33,  1,  6, 20, 16], dtype=int64)

In [26]:
Hut_Paradise_values[:,3]

array([ 5, 12, 10,  3,  6, 13,  8, 21,  5], dtype=int64)

In [27]:
not_liv_area = Hut_Paradise_values[:,1] - Hut_Paradise_values[:,5]
not_liv_area

array([13, 12, 15, 13, 17,  9, 20, 15, 25], dtype=int64)

In [30]:
observe_time = np.array([10,20,30,15,5,40,20,8,20])

In [32]:
observe_time_by_flat = observe_time * Hut_Paradise_values[:,4]
observe_time_by_flat

array([ 80,  80, 150, 150, 100, 480, 100,   8, 200], dtype=int64)

In [33]:
observe_time_by_flat.sum()

1348

In [34]:
u=np.array([3,0,1,1,1])
v=np.array([0,1,0,2,-2])
w=np.array([1,-4,-1,0,-2])

s = 2*v + (-3)*w
s

array([-3, 14,  3,  4,  2])

In [36]:
is_ort = u@s
is_ort

0