In [2]:
import numpy as np

a = np.int8(20)

print(type(a))

<class 'numpy.int8'>


In [3]:


np.iinfo(np.int64)

iinfo(min=-9223372036854775808, max=9223372036854775807, dtype=int64)

In [4]:
import numpy as np
a = np.uint8(-456)

print(a)

56


C:\Users\nitys\AppData\Local\Temp\ipykernel_8644\3196159569.py:2: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of -456 to uint8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)
will give the desired result (the cast overflows).
  a = np.uint8(-456)


In [4]:
import numpy as np

nd_arr = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]   
    ], dtype=np.int8)
nd_arr.dtype

dtype('int8')

In [28]:
import numpy as np

arr = np.array([ 
            [1, 2, 3],
            [3, 4, 5],
            [7, 8, 9]                
            ], dtype=np.int16)

arr.ndim

2

In [40]:
arr = np.linspace(-6, 21, 60, False, True, dtype=np.float16)
print(arr)

(array([-6.  , -5.55, -5.1 , -4.65, -4.2 , -3.75, -3.3 , -2.85, -2.4 ,
       -1.95, -1.5 , -1.05, -0.6 , -0.15,  0.3 ,  0.75,  1.2 ,  1.65,
        2.1 ,  2.55,  3.  ,  3.45,  3.9 ,  4.35,  4.8 ,  5.25,  5.7 ,
        6.15,  6.6 ,  7.05,  7.5 ,  7.95,  8.4 ,  8.85,  9.3 ,  9.75,
       10.2 , 10.65, 11.1 , 11.55, 12.  , 12.45, 12.9 , 13.35, 13.8 ,
       14.25, 14.7 , 15.15, 15.6 , 16.05, 16.5 , 16.95, 17.4 , 17.84,
       18.3 , 18.75, 19.2 , 19.66, 20.1 , 20.55], dtype=float16), 0.45)


In [41]:
a = [1, 2, 3]
print(a[-1])

3


In [63]:
import numpy as np

mystery = np.array([
       [-13586,  15203,  28445, -27117,  -1781, -17182, -18049],
       [ 25936, -30968,  -1297,  -4593,   6451,  15790,   7181],
       [ 13348,  28049,  28655,  -6012,  21762,  25397,   8225],
       [ 13240,   7994,  32592,  20149,  13754,  11795,   -564],
       [-21725,  -8681,  30305,  22260, -17918,  12578,  29943],
       [-16841, -25392, -17278,  11740,   5916,    -47, -32037]
       ], dtype=np.int16)


rev = mystery [::-1, -1]

print(rev)


[-32037  29943   -564   8225   7181 -18049]


In [84]:
import numpy as np
a = np.array( [1, 2, 3, -4, 5, -8])
roots = np.sqrt(a)


print(roots)
n_nan = np.count_nonzero(roots)
print('fsafasf', len(roots) -n_nan)
strange_list = list(np.isnan(roots))
print('STR LIST', strange_list)
print('TYPE STR LIST', type(strange_list))
a = strange_list.count(True)
print('TRUE COUNTER', a)


print(a)
roots[np.isnan(roots)] = 0

print(roots)
print(sum(roots))


[1.         1.41421356 1.73205081        nan 2.23606798        nan]
fsafasf 0
STR LIST [False, False, False, True, False, True]
TYPE STR LIST <class 'list'>
TRUE COUNTER 2
2
[1.         1.41421356 1.73205081 0.         2.23606798 0.        ]
6.382332347441762


C:\Users\nitys\AppData\Local\Temp\ipykernel_25224\3608624834.py:3: RuntimeWarning: invalid value encountered in sqrt
  roots = np.sqrt(a)


In [1]:
import numpy as np

mystery = np.array([ 12279., -26024.,  28745.,  np.nan,  31244.,  -2365.,  -6974., -9212., np.nan, -17722.,  16132.,  25933.,  np.nan, -16431., 29810.], dtype=np.float32)

nans_index = np.isnan(mystery)
strange_list = list(nans_index)
n_nan = strange_list.count(True)
print('N_NAN', '\n', n_nan)

mystery_new = mystery.copy()
mystery_new[np.isnan(mystery_new)] = 0
print('MYSTERY NEW', '\n' , mystery_new)

mystery_int = np.int32(mystery) 

print('MYSTERY INT', '\n', mystery_int)

array = mystery.copy()
array.sort()
print('ARRAY', '\n', array)

table = array.reshape((5, 3), order='F')
print('TABLE', '\n',  table)

col = table[:, 1]
print('COL', '\n',  col)

N_NAN 
 3
MYSTERY NEW 
 [ 12279. -26024.  28745.      0.  31244.  -2365.  -6974.  -9212.      0.
 -17722.  16132.  25933.      0. -16431.  29810.]
MYSTERY INT 
 [      12279      -26024       28745 -2147483648       31244       -2365
       -6974       -9212 -2147483648      -17722       16132       25933
 -2147483648      -16431       29810]
ARRAY 
 [-26024. -17722. -16431.  -9212.  -6974.  -2365.  12279.  16132.  25933.
  28745.  29810.  31244.     nan     nan     nan]
TABLE 
 [[-26024.  -2365.  29810.]
 [-17722.  12279.  31244.]
 [-16431.  16132.     nan]
 [ -9212.  25933.     nan]
 [ -6974.  28745.     nan]]
COL 
 [-2365. 12279. 16132. 25933. 28745.]


C:\Users\nitys\AppData\Local\Temp\ipykernel_24168\4033763485.py:14: RuntimeWarning: invalid value encountered in cast
  mystery_int = np.int32(mystery)


In [3]:
import numpy as np

x = np.array( [1, 4] )
y = np.array( [3, 5] )

print(np.dot(x,y))

23


In [7]:
import numpy as np

a = np.array( [23, 34, 27] ) 
b= np.array( [-54,  1,  46] )
c = np.array( [46, 68, 54] )

ab = a + b
ac = a + c
bc = b + c

lenght_a = np.linalg.norm(a)
lenght_b = np.linalg.norm(b)
lenght_c = np.linalg.norm(c)

lenght_ab = np.linalg.norm(ab)
lenght_ac = np.linalg.norm(ac)
lenght_bc = np.linalg.norm(bc)

# if (lenght_a + lenght_b) == lenght_ab:
#     print ('ab')
    
# if (lenght_a + lenght_c) == lenght_ac:
#     print ('ac')

# if (lenght_c + lenght_b) == lenght_bc:
#     print ('bc')

# distance_ab = np.linalg.norm(a - b)
# distance_ac = np.linalg.norm(a - c)
# distance_bc = np.linalg.norm(b - c)

scalar_ab = np.dot(a,b)
scalar_ac = np.dot(a,c)
scalar_bc = np.dot(b,c)

print(scalar_ab, scalar_ac, scalar_bc)

34 4828 68


In [12]:
a = '481  18 308  13 652 391  63  62 353 111 805 251  36 544 600 799 283 880 \
 470 599 814 507 242 650 180 860 979 298 621 197 572 976 905 427 119 905\
  64 430 742 563 382 211 228 760 567 366 103 409 211 952   5 493 151 267\
 517 495 375  80 341  39 560  85 490  44  17 151  42 688 648 501 437 154\
  66  28 921 642 196 719 208 492 538 687 841 933 386 719 114 261 838 228\
 120 508 316 476 233 902 698 471 604 172 993 790 557 129 446  64 317 997\
 509 710 909 147 228 595 188 246 728 509 365 139 773 426 929 888 534 513\
 666  77 299 943 985 588 137  31 385 405 980 854 327 714 318 909 803 334\
 130 949 532 640 820 975 889 240 878 294 899 488 639 961 819 649 939 163\
 209 879 479 573 557  25 783 332 311 425 140 678 766 492 234 316 811 447\
 772 325 640 387 858 208 739 870 227 385  24 286  22 599 951 994 457  99\
 238 172 549 932 412 545 713  19 785 931 684 333 630 752 191 949 200 361\
 887 243 753 600 635 243 173 249 294 583 106 772 848 387 874 321 562  96\
 211 561 918 868 206 745 710 869 387 600 726 179 336 806 392 612'
b = a.replace(' ', ',')
print(b)

481,,18,308,,13,652,391,,63,,62,353,111,805,251,,36,544,600,799,283,880,,470,599,814,507,242,650,180,860,979,298,621,197,572,976,905,427,119,905,,64,430,742,563,382,211,228,760,567,366,103,409,211,952,,,5,493,151,267,517,495,375,,80,341,,39,560,,85,490,,44,,17,151,,42,688,648,501,437,154,,66,,28,921,642,196,719,208,492,538,687,841,933,386,719,114,261,838,228,120,508,316,476,233,902,698,471,604,172,993,790,557,129,446,,64,317,997,509,710,909,147,228,595,188,246,728,509,365,139,773,426,929,888,534,513,666,,77,299,943,985,588,137,,31,385,405,980,854,327,714,318,909,803,334,130,949,532,640,820,975,889,240,878,294,899,488,639,961,819,649,939,163,209,879,479,573,557,,25,783,332,311,425,140,678,766,492,234,316,811,447,772,325,640,387,858,208,739,870,227,385,,24,286,,22,599,951,994,457,,99,238,172,549,932,412,545,713,,19,785,931,684,333,630,752,191,949,200,361,887,243,753,600,635,243,173,249,294,583,106,772,848,387,874,321,562,,96,211,561,918,868,206,745,710,869,387,600,726,179,336,806,392,612

In [27]:
import numpy as np

np.random.rand(2, 2, 2, 2)

array([[[[0.39318533, 0.38745121],
         [0.61098658, 0.44448917]],

        [[0.91092597, 0.57298919],
         [0.81009036, 0.32079261]]],


       [[[0.13148197, 0.09949626],
         [0.32063647, 0.3298567 ]],

        [[0.67669909, 0.28897683],
         [0.72886923, 0.627995  ]]]])

In [45]:
import numpy as np
np.random.seed(2021)

simple = np.random.rand()
#print(simple)

randoms = np.random.uniform(-150, 2022, size=120)
#print(randoms)

table = np.random.randint(1, 101, size=(3, 2)) 
#print(table)

even = np.arange(2, 17, 2)
#print(even)

mix = np.random.permutation(even)
#print(mix)

select = np.random.choice(even, size=3, replace=False)
#print(select)

triplet = np.random.permutation(select)
#print(triplet)



[ 2  4 14]


In [86]:
import numpy as np

a = 8
def get_chess(a):
    arr = np.zeros((a,a))
    arr[::2 , 1::2] = 1
    arr[1::2 , ::2] = 1
    
    return arr

print(get_chess(a))

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [100]:
import numpy as np
from random import randint
#array = np.array( [1, 2, 3]) 
def shuffle_seed(array):
    rand_for_seed = randint(0, 2**32)
    return (array, rand_for_seed)

print(shuffle_seed(array))

(array([1, 2, 3]), 2159249477)


In [12]:
import numpy as np

def min_max_dist(*vectors):
    min_max = np.array( [] )
    print(type(vectors[0]))
    print(min_max)
    
    
    
    

vec1 = np.array([1,2,3])
vec2 = np.array([4,5,6])
vec3 = np.array([7, 8, 9])

min_max_dist(vec1, vec2, vec3)
# (5.196152422706632, 10.392304845413264)


SyntaxError: invalid syntax (1928039531.py, line 4)

In [133]:
a, b, c = 2, 3, 4

def testi(*args):
    print(args)
    a = len(args)
    print(range(a-1))
    for i in range(a):
        
        print(map(args[i]* args[(i+1):a]))
    return args

print(testi(a,b,c))

(2, 3, 4)
range(0, 2)


TypeError: map() must have at least two arguments.

In [111]:
from collections import OrderedDict

a = [ (1, 2), (3, 4), (5, 1) ]

b = OrderedDict(sorted(a, key= lambda x: x[1], reverse=True))

print(b)

OrderedDict({3: 4, 1: 2, 5: 1})


In [15]:
import numpy as np

a = np.array([3, 4, 5, 6])
b = np.array([7, 8, 9, 1])
c = np.array([1, 2, 5, 6])

def testi_kw(*args):
    final_arr = list()
    #print(final_arr)
    for i in range(len(args)):
        empty_ar = list(map( lambda x: args[i] * x, args ))
        empty_ar.pop(i)
        ar_for_upd = empty_ar.copy()
        #print(ar_for_upd)
        final_arr += ar_for_upd
        
    return (final_arr)


# b = list(map( lambda x: a[0] * x, a) )
# print(b)
# print(type(a[0]))
# print(c)

print(testi_kw(a, b, c))

[array([21, 32, 45,  6]), array([ 3,  8, 25, 36]), array([21, 32, 45,  6]), array([ 7, 16, 45,  6]), array([ 3,  8, 25, 36]), array([ 7, 16, 45,  6])]


In [2]:
import numpy as np

# a = np.array([3, 4, 5, 6])
# b = np.array([7, 8, 9, 1])
# c = np.array([1, 2, 5, 6])

def min_max_dist(*vectors):
    final_arr = list()
    #print(final_arr)
    for i in range(len(vectors)):
        empty_ar = list(map( lambda x: np.linalg.norm( vectors[i] - x ), vectors ))
        empty_ar.pop(i)
        ar_for_upd = empty_ar.copy()
        #print(ar_for_upd)
        final_arr += ar_for_upd
        
    return ( min(final_arr), max(final_arr) )

print(min_max_dist(np.array([1, 2, 3]), np.array([4, 5, 6]), np.array([7, 8, 9])))

#print(min_max_dist(a, b, c))

(5.196152422706632, 10.392304845413264)


In [5]:
import numpy as np


def any_normal(*vectors):
    final_arr = list()
    #print(final_arr)
    for i in range(len(vectors)):
        empty_ar = list(map( lambda x: np.dot( vectors[i], x ), vectors ))
        empty_ar.pop(i)
        if 0 in empty_ar:
            return True
        else: 
            return False

print(any_normal(np.array([1, 2, 3]), np.array([4, 5, 6]), np.array([7, 8, 9])))

#print(min_max_dist(a, b, c))

False


In [4]:
from random import randint
import numpy as np


def get_loto(num):
    arr = np.zeros((num* 5* 5))
    for i in range(len(arr)): 
        arr[i] = randint(1, 101)  
    brr = arr.reshape((num, 5, 5))
    return brr
    
print(get_loto(3))
    
    

[[[ 56.  58.   5.  89.   8.]
  [ 69. 100.  44.  10.  92.]
  [ 35.  48.  16.  30.  13.]
  [ 44.  77.  81.  24.   7.]
  [ 78.  82.  86.  34.   6.]]

 [[ 16.  81.  59.   3. 100.]
  [ 14.  52.  64.  73.  54.]
  [ 49.  68.  93.   3.  26.]
  [ 50.  12.  33.   6.  80.]
  [ 95.  83.  66.  76.  78.]]

 [[ 61.  10.  35.  55.  27.]
  [ 68.  74.  91.  75.  36.]
  [  9.  73.  17.  12.  41.]
  [ 26.  86.  87.  18.  37.]
  [ 50.  42.  34.  16.  67.]]]


In [2]:
import pandas as pd

countries = pd.Series(
    data = ['Англия', 'Канада', 'США', 'Россия', 'Украина', 'Беларусь', 'Казахстан'],
    index = ['UK', 'CA', 'US', 'RU', 'UA', 'BY', 'KZ'],
    name = 'countries'
)
display(countries)

UK       Англия
CA       Канада
US          США
RU       Россия
UA      Украина
BY     Беларусь
KZ    Казахстан
Name: countries, dtype: object

In [1]:
import numpy as np


def get_unique_loto(num):
    new_arr = np.zeros((num,5,5))
    # for i in range(num-3):
    #     print('Count')
    new_arr += (np.random.choice(np.arange(1, 101), size=(5,5), replace=False))        
    return new_arr

print(get_unique_loto(4))
    

[[[11. 16. 25. 54. 86.]
  [97.  5. 50. 45. 13.]
  [90. 98. 42. 12. 34.]
  [17. 37. 46. 31. 47.]
  [65. 72. 18. 69. 39.]]

 [[11. 16. 25. 54. 86.]
  [97.  5. 50. 45. 13.]
  [90. 98. 42. 12. 34.]
  [17. 37. 46. 31. 47.]
  [65. 72. 18. 69. 39.]]

 [[11. 16. 25. 54. 86.]
  [97.  5. 50. 45. 13.]
  [90. 98. 42. 12. 34.]
  [17. 37. 46. 31. 47.]
  [65. 72. 18. 69. 39.]]

 [[11. 16. 25. 54. 86.]
  [97.  5. 50. 45. 13.]
  [90. 98. 42. 12. 34.]
  [17. 37. 46. 31. 47.]
  [65. 72. 18. 69. 39.]]]


In [27]:
import numpy as np
arr = np.array(2,2)
print(arr)

TypeError: Cannot interpret '2' as a data type

In [6]:
from collections import Counter
simplelist = [19, 242, 14, 152, 142, 1000]

c = Counter(simplelist)
print(c)

a = sum(c.keys())/len(simplelist)
print(a)

Counter({19: 1, 242: 1, 14: 1, 152: 1, 142: 1, 1000: 1})
261.5
